#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet,  configures a server to listening on port 80 of all servers active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
